name: Docker Workflow
on:
  create:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Run hadolint
      run: docker run --rm -i hadolint/hadolint:v1.17.5-alpine < .
    - name: Install dependencies
      run: npm install --prefix path/to/package.json


    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ github.repository }}:${{ github.ref }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

