name: Flux de travail de test

on:
  push:
    branches:
      - super_calculator

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: [1.17, 1.18, 1.19]

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v2
      
      - name: Configuration de Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Exécuter les tests unitaires
        run: go test ./...

